version: "3"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql
    tty: true
